-- ESPELHO DE MIGRACAO APLICADA
-- version: 20260803185317
-- name: gt26_identity_config_e_gt36_split_tetos
-- projeto: gzjwnjdpxpbmdhcyefvs (Gestor de Trafego IA)
-- aplicada por: Claude via MCP apply_migration
-- espelho gerado a partir de supabase_migrations.schema_migrations - NAO transcrito a mao

-- 03/08/2026 - GT-26 e GT-36.

-- ============================================================
-- GT-26: cicatriz do singleton. meta_execution_config.id era PRIMARY KEY com DEFAULT 1.
-- A v3 da meta-actions removeu o CHECK que travava id=1 e deixou o DEFAULT. Consequencia
-- pratica: a tela "Nova empresa" NAO conseguia criar a configuracao da empresa - colidia na
-- chave. A linha da terceira empresa (Cooperativa_ Cohapm) so entrou porque foi inserida com
-- MAX(id)+1 explicito, na mao, em 03/08.
-- ============================================================
ALTER TABLE public.meta_execution_config ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.meta_execution_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public.meta_execution_config','id'),
              (SELECT COALESCE(MAX(id),0) FROM public.meta_execution_config));

-- A config e UMA por empresa. Sem esta trava, duas linhas para a mesma empresa fariam o
-- maybeSingle() do executor sortear qual travas valem - bug latente pior que o original.
-- NOT NULL antes do UNIQUE: NULL nao colide em unique, entao unique sozinho nao garante nada.
ALTER TABLE public.meta_execution_config ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE public.meta_execution_config
  ADD CONSTRAINT uq_meta_execution_config_company UNIQUE (company_id);

-- ============================================================
-- GT-36: o fato 39 misturava METODO e NUMEROS de duas empresas. Ao escopar 39 para a Legal e
-- Viver no GT-27, a COHAPM perdeu o acesso ao metodo E aos proprios numeros, que estavam
-- dentro dele. Consequencia declarada no espelho da migracao 20260803141646 e agora resolvida:
-- o metodo vira GLOBAL sem numero nenhum, e cada empresa fica com os seus.
-- ============================================================

-- (a) METODO, global, sem numero. Vale para qualquer anunciante.
INSERT INTO agent_context (categoria, fato, vigente, desde, atualizado, company_id)
VALUES ('metodo',
  'COMO OS TETOS DE CUSTO DESTE SISTEMA SAO PRODUZIDOS - METODO, VALIDO PARA QUALQUER EMPRESA. '
  || 'Teto NAO e meta de negocio: e DERIVADO do proprio historico da conta, pela regra "percentil 75 '
  || 'do custo diario, considerando apenas dias com gasto maior ou igual a 10". '
  || 'DUAS ARMADILHAS A DECLARAR SEMPRE QUE USAR UM TETO: '
  || '(1) por ser derivado do historico, o teto mede CONSISTENCIA e nao rentabilidade - "dentro do teto" '
  || 'significa "sem desvio em relacao ao proprio passado da conta", NUNCA "da retorno"; '
  || '(2) o calculo foi feito UMA UNICA VEZ em 22/07/2026 e envelhece em silencio - se produto, publico '
  || 'ou concorrencia mudaram, o teto pode estar defasado para cima ou para baixo. Ao usar, diga a data '
  || 'do calculo. ATUALIZACAO 03/08/2026: o gestor Roberto definiu que o recalculo passa a ser SEMANAL '
  || '(audio 03/08 14:47) - enquanto a rotina de recalculo nao existir, o numero segue congelado em '
  || '22/07 e isso deve ser declarado. Revisar teto e decisao humana com dono e data, nunca consequencia '
  || 'automatica. AMOSTRA PEQUENA (poucos dias com gasto) torna o teto pouco confiavel: declare o numero '
  || 'de dias junto do valor.',
  true, '2026-08-03', now(), NULL);

-- (b) NUMEROS da Legal e Viver, sem repetir o metodo.
UPDATE agent_context SET
  atualizado = now(),
  fato = 'TETOS DE CUSTO DA LEGAL E VIVER (calculados 22/07/2026, auditados 29/07/2026). '
      || 'Custo por formulario R$ 2,30 (mediana 2,03 / p90 2,66 / amostra 70 dias). '
      || 'Custo por lead de landing page R$ 1,50 (amostra 159 dias) - LEMBRE que "lead de LP" nesta conta '
      || 'e CLIQUE NO LINK, nome historico enganoso. '
      || 'Custo por conversa R$ 1,55 (amostra 37 dias) - metrica de WhatsApp, e desde 03/08/2026 o gestor '
      || 'declarou que NENHUMA campanha nova vai para WhatsApp, entao este teto e legado. '
      || 'O METODO de derivacao e as armadilhas estao no fato global sobre producao de tetos - nao repita '
      || 'o metodo aqui, e nunca cite um destes numeros sem a ressalva de que teto mede consistencia e '
      || 'nao rentabilidade.'
WHERE id = 39;

-- (c) NUMEROS da COHAPM, que estavam dentro do fato 39 e ficaram sem dono ao escopa-lo.
--     Empresa buscada por NOME: identificador digitado a mao e como literal escrito a mao - erra.
INSERT INTO agent_context (categoria, fato, vigente, desde, atualizado, company_id)
SELECT 'metodo',
  'TETOS DE CUSTO DA COHAPM (calculados 22/07/2026, auditados 29/07/2026) - USE COM RESSALVA FORTE. '
  || 'Custo por conversa R$ 21,80 (amostra 12 dias). Custo por lead de landing page R$ 6,85 (amostra 13 dias). '
  || 'AS DUAS AMOSTRAS SAO PEQUENAS e os tetos, portanto, POUCO CONFIAVEIS - declare o numero de dias '
  || 'sempre que citar. Os tetos da COHAPM sao proprios e muito diferentes dos da Legal e Viver, o que e '
  || 'esperado: sao produtos e categorias regulatorias distintas. NUNCA compare o custo da COHAPM com o '
  || 'da Legal e Viver, e nunca aplique teto de uma a outra. O METODO de derivacao esta no fato global '
  || 'sobre producao de tetos.',
  true, '2026-08-03', now(), c.id
FROM companies c
WHERE c.name = 'COHAPM'
  AND NOT EXISTS (
    SELECT 1 FROM agent_context a
     WHERE a.company_id = c.id AND a.vigente AND a.fato ILIKE '%TETOS DE CUSTO DA COHAPM%');