-- GT-24: toda empresa nasce com postura Meta segura, antes de vincular uma conta.
-- O vínculo via integration-verify só troca o driver e adiciona a conta permitida;
-- master_enabled=false e dry_run=true continuam sendo os defaults bloqueantes.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_attribute
    where attrelid = 'public.meta_execution_config'::regclass
      and attname = 'id'
      and attidentity in ('a', 'd')
  ) then
    alter table public.meta_execution_config
      alter column id add generated by default as identity;
  end if;
end
$$;

do $$
declare
  v_sequence text;
  v_max bigint;
begin
  v_sequence := pg_get_serial_sequence('public.meta_execution_config', 'id');
  select coalesce(max(id), 0) into v_max from public.meta_execution_config;
  if v_sequence is not null and v_max > 0 then
    perform setval(v_sequence, v_max, true);
  end if;
end
$$;

create or replace function private.bootstrap_meta_execution_config()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.meta_execution_config (company_id)
  values (new.id)
  on conflict (company_id) do nothing;
  return new;
end;
$$;

revoke all on function private.bootstrap_meta_execution_config() from public, anon, authenticated;

drop trigger if exists trg_companies_bootstrap_meta_execution_config on public.companies;
create trigger trg_companies_bootstrap_meta_execution_config
after insert on public.companies
for each row execute function private.bootstrap_meta_execution_config();

insert into public.meta_execution_config (company_id)
select c.id
from public.companies c
where not exists (
  select 1
  from public.meta_execution_config mec
  where mec.company_id = c.id
);
