-- Registro de ferramentas: a definicao sai do prompt e vira dado (03/09/2026)
--
-- POR QUE. Medicao de hoje, antes desta migration:
--   traffic-chat  systemPrompt()  45.059 chars (~12.5 mil tokens) em TODO turno
--   traffic-chat  const TOOLS     46.353 chars (~12,9 mil tokens), 27.893 so de descricao
--   traffic-agent-job  const DEF  19.794 chars (~5,5 mil tokens)
-- As descricoes viraram deposito de doutrina: "PROIBIDO...", "NUNCA...", data de incidente e
-- excecao, tudo indo ao modelo em todo turno, chamada a ferramenta ou nao. E as MESMAS 42
-- ferramentas tinham uma descricao no chat e outra no job, divergindo em silencio.
--
-- Alem disso, get_detalhe_anuncios e origem_drive_dos_anuncios existiam no codigo do chat e
-- NAO existiam em agent_unidades. Como o Roteador estreita o turno pelo registro, um pedido
-- de serie diaria por anuncio saia sem a ferramenta que a propria doutrina chama de
-- obrigatoria — o defeito de 02/09, quando 5 de 6 anuncios sairam "sem vinculo de pasta"
-- embora os cards tivessem pasta e drive_file_id.
--
-- O DESENHO. Tres camadas, e elas nao se misturam:
--   descricao  decide SE a ferramenta e chamada. Vai ao modelo em todo turno em que a
--              ferramenta esta na mesa. Curta por obrigacao.
--   parametros o schema, unico para as duas superficies.
--   doutrina   decide COMO ler o retorno. NAO entra em prompt nenhum: as edges colam esse
--              texto na mensagem de retorno da ferramenta, e so quando ela foi executada.
--              Tambem NAO e persistida no tool_results, entao nao volta na reinjecao de
--              historico dos turnos seguintes. Paga-se uma vez, na rodada em que serve.
--
-- ONDE A LINHA E DURA: num turno degradado (leitura desta tabela falhou) as edges caem no
-- snapshot local _shared/ferramentas_base.ts, que traz descricao e parametros mas NAO a
-- doutrina. Por isso toda guarda que decide se um ato acontece ficou na descricao ou no
-- system prompt. A doutrina carrega interpretacao de retorno, nao trava de ato.
--
-- O VINCULO agente<->ferramenta continua em agent_unidades (tipo='ferramenta'). Esta tabela
-- responde "o que a ferramenta e"; aquela responde "de quem ela e". Duas perguntas, dois
-- lugares, nenhuma verdade duplicada.

create table if not exists public.agent_ferramentas (
  chave                text primary key,
  descricao            text not null,
  parametros           jsonb not null,
  doutrina             text,
  -- Onde a ferramenta existe. O handler e que manda: anunciar 'job' para algo que o runTool
  -- do job nao implementa faria o subagente chamar uma ferramenta que nao existe.
  superficies          text[] not null default array['chat']::text[],
  -- Propriedades que o handler DAQUELA superficie ignora. Declaracao de capacidade, nao
  -- schema paralelo: anunciar um filtro que o handler descarta faz o modelo acreditar num
  -- recorte que nunca aconteceu.
  parametros_omitidos  jsonb not null default '{}'::jsonb,
  vigente              boolean not null default true,
  criado_em            timestamptz not null default now(),
  atualizado_em        timestamptz not null default now()
);

comment on table public.agent_ferramentas is
  'Definicao de cada ferramenta (nome, descricao curta, schema, doutrina de uso). Substitui os arrays TOOLS/DEF hardcoded nas edges. Fallback local em supabase/functions/_shared/ferramentas_base.ts.';
comment on column public.agent_ferramentas.descricao is
  'O que decide SE a ferramenta e chamada. Vai ao modelo em todo turno em que ela esta na mesa.';
comment on column public.agent_ferramentas.doutrina is
  'O que decide COMO ler o retorno. Injetada colada ao retorno, so quando a ferramenta roda, e nunca persistida no historico.';

alter table public.agent_ferramentas enable row level security;

-- Mesma postura de public.agents: leitura para quem esta autenticado, escrita so pelo
-- service role das edges. O catalogo nao e segredo; o que nao pode e ser editavel pelo app.
drop policy if exists "agent_ferramentas leitura autenticada" on public.agent_ferramentas;
create policy "agent_ferramentas leitura autenticada"
  on public.agent_ferramentas for select to authenticated using (true);

insert into public.agent_ferramentas
  (chave, descricao, parametros, doutrina, superficies, parametros_omitidos)
values
  ($ft$alterar_categoria_especial$ft$, $ft$Emite CARD DE APROVACAO para alterar ou REMOVER special_ad_categories de uma campanha JA CRIADA. Passe special_ad_categories=[] para remover. NAO diga que falta ferramenta para isso nem que so da na criacao.$ft$, $ft${"type":"object","properties":{"campanha_atual":{"type":"string"},"special_ad_categories":{"type":"array","items":{"type":"string"}},"categorias_atuais":{"type":"array","items":{"type":"string"}},"justificativa":{"type":"string"}},"required":["campanha_atual","special_ad_categories"]}$ft$::jsonb, $ft$Leia o estado antes com get_campaign_detail ou auditar_compliance_financeira. A Meta aplica a categoria na campanha e os anuncios herdam.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$auditar_compliance_financeira$ft$, $ft$Auditoria de categoria especial e regras financeiras de UMA campanha e seus anuncios (name_like). Use quando o gestor perguntar se os anuncios respeitam financas, categoria especial ou regras da Meta. NAO diga que o campo nao existe: esta tool e get_campaign_detail leem.$ft$, $ft${"type":"object","properties":{"name_like":{"type":"string","description":"Nome (ou trecho) da campanha"}},"required":["name_like"]}$ft$::jsonb, $ft$Devolve special_ad_categories do espelho, se e financeira, a lista de anuncios (status, CTA, destino, criado_pelo_sistema), alertas de segmentacao (idade, genero, LAL) e as regras ativas FIN/LGL/CRI. Complemente com get_conhecimento(tema=compliance) para a politica e check_compliance para as legendas; confirmacao ao vivo em ler_pipeboard get_campaign_details.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$avaliar_escala$ft$, $ft$Avalia se um conjunto esta apto a escala por duplicacao com no maximo +20%, usando a arvore de decisao, custo ate 80% do teto, volume e espera. Exige adset_external_id.$ft$, $ft${"type":"object","properties":{"adset_external_id":{"type":"string"}},"required":["adset_external_id"]}$ft$::jsonb, $ft$Nao cobre CBO sem orcamento proprio. A espera enxerga apenas escalas registradas pelo sistema, nao alteracoes feitas a mao no Gerenciador.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$avaliar_fadiga$ft$, $ft$Avalia se uma peca cansou, teve queda sem saturacao, esta com frequencia alta antes da queda ou nao tem sinal de fadiga. Exige ad_external_id.$ft$, $ft${"type":"object","properties":{"ad_external_id":{"type":"string"}},"required":["ad_external_id"]}$ft$::jsonb, $ft$Sem entrega ou sem base nao conclui. Usa frequencia DIARIA e declara que a frequencia deduplicada de 30 dias NAO pode ser derivada das linhas diarias.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$avaliar_pacing$ft$, $ft$Calcula a capacidade diaria da estrutura e, se meta_leads_dia for informada, o PISO de verba diaria ao custo atual.$ft$, $ft${"type":"object","properties":{"meta_leads_dia":{"type":"number"}}}$ft$::jsonb, $ft$Declara que nao existe meta registrada. A projecao NAO e estimativa: escalar tende a elevar o custo, entao a verba real pode ser maior.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$buscar_geolocalizacao$ft$, $ft$Resolve NOMES de bairro, cidade ou regiao para KEYS da Meta (Graph /search type=adgeolocation). Chame ANTES de criar_conjunto com geo fino. Lote maximo de 40 nomes por chamada. Default tipo=neighborhood, country_code=BR. NAO cria conjunto e NUNCA diga que falta campo de bairros.$ft$, $ft${"type":"object","properties":{"nomes":{"type":"array","items":{"type":"string"},"description":"Lista de nomes (ate 40 por chamada)."},"tipo":{"type":"string","description":"neighborhood|city|region|zip (default neighborhood)."},"country_code":{"type":"string","description":"Default BR."},"cidade_contexto":{"type":"string","description":"Opcional: filtra ambiguidade (ex. Salvador)."}},"required":["nomes"]}$ft$::jsonb, $ft$Devolve resolvidos, ambiguos, nao_encontrados, geo_locations_sugerido e bairros_keys, que entram em params.bairros ou params.geo_locations do propose_action criar_conjunto_a_partir_de. Para ~118 bairros, chame em lotes e una os bairros_keys. Presets em geo_targeting_presets sao POR empresa e meio: outra empresa ou outro meio NAO herda. Em credito (fair lending), bairro e CEP podem ser recusados no gate.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$casar_criativo_performance$ft$, $ft$ESP-33: casa peca do Drive com os anuncios criados PELO SISTEMA a partir dela e devolve as metricas da janela. Passe drive_file_id e/ou ad_external_id; sem filtro lista os pares existentes. Use antes de julgar peca do acervo por desempenho. Para a pasta de origem de um CONJUNTO inteiro, use origem_drive_dos_anuncios.$ft$, $ft${"type":"object","properties":{"drive_file_id":{"type":"string"},"ad_external_id":{"type":"string"},"dias":{"type":"integer","description":"Janela em dias (default 7)."}}}$ft$::jsonb, $ft$Se os DOIS filtros zerarem, a tool reconsulta so pelo anuncio e devolve o par real: leia o aviso e NAO trate vazio como 'sem origem'. Anuncios feitos so no Gerenciador nao entram — lacuna declarada. amostra_pequena (menos de 20 resultados) vira hipotese, nao veredito, e ranking medio isolado nao prescreve pausa.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$checar_par_texto_e_peca$ft$, $ft$Avalia o PAR legenda + peca pela concatenacao do texto disponivel. Exige legenda e drive_file_id; passe campanha e conjunto quando for emitir. Existe caminho conjunto: nunca diga que o par nao e avaliado.$ft$, $ft${"type":"object","properties":{"legenda":{"type":"string"},"drive_file_id":{"type":"string"},"campanha":{"type":"string","description":"Nome da campanha destino (COHAPM: obriga casar linha da peca)."},"conjunto":{"type":"string","description":"Nome do conjunto destino."},"nome_criativo":{"type":"string"}},"required":["legenda","drive_file_id"]}$ft$::jsonb, $ft$Veredito por deteccao de padroes, NAO aprovacao. Audio sem transcricao permanece explicitamente nao lido; repasse cobertura e lacunas. Se so um dos dois veio, peca o dado faltante sem negar a capacidade. COHAPM: campanha/conjunto de uma linha com peca de outra (Juridico vs La Felicita vs VISTTA) REPROVA — ERRO GRAVE, nao aviso.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$check_compliance$ft$, $ft$GUARDIAO DE COMPLIANCE: valida deterministicamente UMA legenda (texto integral) e/ou a peca anexada contra as regras versionadas. Esboco que VOCE escreveu nesta conversa: passe o proprio texto em legenda=. Anuncio ja publicado: pegue a legenda em get_criativos_conteudo. Passe campanha, conjunto e nome_criativo ao auditar destino x peca.$ft$, $ft${"type":"object","properties":{"legenda":{"type":"string","description":"Texto integral da legenda a validar (obrigatorio se nao houver imagem anexada)."},"campanha":{"type":"string"},"conjunto":{"type":"string"},"nome_criativo":{"type":"string"},"drive_file_id":{"type":"string"},"meio":{"type":"string","enum":["la_felicita","juridico","sistema_ocular"]}},"required":["legenda"]}$ft$::jsonb, $ft$NAO use get_criativos_conteudo vazio como desculpa de '0 textos para validar' nem diga que precisa sincronizar a Meta para auditar copy que voce acabou de propor (21/08/2026). COHAPM: campanha ou conjunto Juridico com peca La Felicita, ou o inverso, REPROVA — ERRO GRAVE, nao aviso. Se o NOME da peca ja e da linha certa e so a LEGENDA vazou a voz de outra, o erro e voz_linha_errada: reescreva a copy na voz do destino e reemita na MESMA campanha, sem trocar de linha.$ft$, array['chat','job']::text[], $ft${"job":["meio","drive_file_id"]}$ft$::jsonb),
  ($ft$computar_perfil_vencedor$ft$, $ft$ESP-34: computa e VERSIONA o perfil do vencedor da empresa e devolve a versao gravada. Use para consolidar ou atualizar 'o que esta vencendo'. Dedup no mesmo dia, salvo forcar=true.$ft$, $ft${"type":"object","properties":{"dias":{"type":"integer","description":"Janela em dias (default 7)."},"forcar":{"type":"boolean","description":"Regrava mesmo se identico ao perfil de hoje (default false)."}}}$ft$::jsonb, $ft$Usa a MESMA regua de evaluate_winners/ESP-01 (janela, no minimo 30 resultados e 30 de gasto, custo menor ou igual a teto_vigente vezes 0,80) e enriquece com a peca do Drive de origem (ESP-33). NAO publica nada, NAO substitui get_recommendations (fila acionavel) e NAO dispensa aprovacao humana de escala — vencedor mora em ESCALA (ESP-39).$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$custo_llm_periodo$ft$, $ft$Custo em USD derivado dos tokens gravados de chat e jobs no periodo (de/ate em YYYY-MM-DD).$ft$, $ft${"type":"object","properties":{"de":{"type":"string","description":"Data inicial YYYY-MM-DD."},"ate":{"type":"string","description":"Data final YYYY-MM-DD."}},"required":["de","ate"]}$ft$::jsonb, $ft$NAO e custo faturado. Declare as premissas do retorno: modelos presumidos, cache pode ser cobrado como teto, ha subagentes sem tokens gravados, e visao e compliance-check ficam invisiveis.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$decidir_sobre_conjunto$ft$, $ft$Decide manter, maturar, trocar criativo ou preparar reversao para um conjunto, usando custo, volume e tendencia. Exige adset_external_id.$ft$, $ft${"type":"object","properties":{"adset_external_id":{"type":"string"}},"required":["adset_external_id"]}$ft$::jsonb, $ft$A guarda do unico conjunto entregando sobrescreve pausa. Lacuna declarada: sem regua de IDEAL separada do teto, esta funcao nao prescreve escala.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$diagnosticar_custo$ft$, $ft$Diagnostica por que o custo por formulario de um anuncio subiu, comparando o ultimo dia com entrega aos 3 anteriores. Exige ad_external_id.$ft$, $ft${"type":"object","properties":{"ad_external_id":{"type":"string"}},"required":["ad_external_id"]}$ft$::jsonb, $ft$Devolve sinal, causa, acao, confirmacao, medidas e guarda de maturacao. Sem base nao conclui, e problema depois do clique e apenas apontado, porque esta fora do escopo.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$gerar_legendas$ft$, $ft$ESP-37, MOTOR DE LEGENDA: gera exatamente 3 variantes Hook -> Beneficio/prova -> CTA e grava em conversation_legendas. NAO cria anuncio. objetivo e obrigatorio; passe produto, meio e o drive_file_id do slate (get_slate_da_conversa).$ft$, $ft${"type":"object","properties":{"produto":{"type":"string","description":"Ex.: imovel / la_felicita, juridico_whatsapp (COHAPM Juridico) ou consignado_clt (Legal). SEM default CLT."},"objetivo":{"type":"string","description":"O que a legenda deve comunicar (obrigatorio)."},"eixo":{"type":"string","description":"Sinonimo de objetivo."},"meio":{"type":"string","enum":["la_felicita","juridico","sistema_ocular"],"description":"Voz da marca. La Felicita = la_felicita."},"drive_file_id":{"type":"string","description":"Peca do Drive (do slate)."},"peca_chave":{"type":"string","description":"Chave estavel. Default = drive_file_id ou objetivo."},"referencias":{"type":"array","items":{"type":"string"},"description":"Ate 5 legendas de referencia (estilo)."}},"required":["objetivo"]}$ft$::jsonb, $ft$Entregue as 3 com veredito: apto_para_card=true inclui aprovado e atencao. CET e FIN-04 valem SO em empresa de credito — nao invente CLT nem CET para COHAPM, e nao assuma produto consignado por default. La Felicita: produto=imovel + meio=la_felicita, e PROIBIDO voz Juridico. VOCE preenche as referencias. Se a tool falhar, NAO diga que a ferramenta esta indisponivel e NAO ofereca ao gestor esperar ou escrever ele mesmo: escreva as 3 no tom certo e registre com registrar_legenda_da_conversa.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$get_acervo_para_anuncio$ft$, $ft$LEITURA do acervo do Drive para montar anuncio, com os ids da Meta e na_biblioteca_da_meta por peca. Em lote ou mix, chame SEM produto na primeira vez; quando o slate ja tem drive_file_ids, passe-os. Esta e a fonte para escolher peca do acervo — get_criativos_conteudo so tem anuncios ja no ar.$ft$, $ft${"type":"object","properties":{"produto":{"type":"string","description":"Opcional. Em lote/mix deixe vazio na 1a chamada."},"incluir_inaptas":{"type":"boolean","description":"Padrao true."},"drive_file_ids":{"type":"array","items":{"type":"string"},"description":"Opcional. Recorte: so estes arquivos (slate conhecido)."},"meio":{"type":"string","enum":["la_felicita","juridico","sistema_ocular"]},"formatos":{"type":"array","items":{"type":"string"}}}}$ft$::jsonb, $ft$Com recorte (meio, formatos, ou o proprio pedido) o inventario_global E o RECORTE, e o total da empresa fica em inventario_global_empresa: NAO cite o total da empresa como se fosse o de uma linha de produto. apta=true significa apenas 'pronta pra publicar agora' e NAO autoriza afirmar escassez; filtro por produto tambem nao autoriza dizer 'so existem N'. Se na_biblioteca_da_meta=false, chame upload_midia antes do card.
PROTOCOLO DE LOTE OU MIX (ex.: '10 criativos', 'mix video+foto+carrossel'): (1) leitura SEM produto primeiro, citando taxonomia_drive e inventario_global — a leitura de referencia da COHAPM trouxe 19 videos (10 de Educacao financeira + 9 de Caminho Triste/feliz), mais Capas, 9 Carrosseis e 4 Cards instrucionais; (2) so depois filtre por produto; (3) Capas (Videos/Educacao financeira/Capa) entram sempre no inventario; (4) Cards sao mecanismo instrucional 'leia a legenda', nao imagem generica; (5) complemente com get_drive_criativos se precisar do caminho da pasta. Em 07/08/2026 o anuncio R06 que ja estava no ar foi proposto no lugar de uma peca nova porque a escolha saiu de get_criativos_conteudo: para montar anuncio novo a fonte e esta leitura, nao a dos anuncios publicados.$ft$, array['chat','job']::text[], $ft${"job":["drive_file_ids"]}$ft$::jsonb),
  ($ft$get_ads_ranking$ft$, $ft$Ranking de criativos por gasto, alcance_soma_diaria, conversas, impressoes ou custo. Use ordenar_por=alcance quando perguntarem maior alcance. Recorte com name_like ou campaign_id (ID Meta) e passe date_from/date_to da janela. PROIBIDO dizer que alcance esta indisponivel sem chamar isto.$ft$, $ft${"type":"object","properties":{"days":{"type":"number"},"ordenar_por":{"type":"string","description":"gasto|alcance|conversas|impressoes|custo"},"date_from":{"type":"string"},"date_to":{"type":"string"},"name_like":{"type":"string"},"campaign_id":{"type":"string"},"somente_ativas":{"type":"boolean"}}}$ft$::jsonb, $ft$Custo medio sozinho NAO autoriza pausa (Breakdown Effect).$ft$, array['chat','job']::text[], $ft${"chat":["somente_ativas"]}$ft$::jsonb),
  ($ft$get_alerts$ft$, $ft$Alertas ativos do sistema (CPL, entrega, BM/politica, cobranca, WABA).$ft$, $ft${"type":"object","properties":{}}$ft$::jsonb, null, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_analise_visual_drive$ft$, $ft$VEREDITO VISUAL POR PECA das midias do Drive, ja persistido pelo especialista de visao: produto detectado pelos pixels, texto visivel, risco e veredito aproveitavel sim/nao/incerto com motivo. Use quando o gestor pedir para classificar as pecas da pasta. Recorte por meio e formatos.$ft$, $ft${"type":"object","properties":{"meio":{"type":"string","enum":["la_felicita","juridico","sistema_ocular"]},"formatos":{"type":"array","items":{"type":"string"}}}}$ft$::jsonb, $ft$Leitura instantanea: nao repete a visao. Se total_analisados for menor que o inventario, ha pecas novas que ainda nao passaram pela visao — declare, nao invente. Serve para inventario e triagem: para julgar UMA peca especifica chame nota_visual_da_peca com o drive_file_id atual. De video, a visao ve UM FRAME.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_aprovacoes$ft$, $ft$FILA REAL DE PEDIDOS DE APROVACAO desta empresa: estado, conjunto, destino_url do criativo e destination_type do conjunto. Chame ANTES de afirmar o estado de um card, se algo foi criado, se o anuncio tem o mesmo link do conjunto, ou o que esta pendente. Pergunta com '?' sem verbo de emitir se responde com esta tool, nao com propose_action.$ft$, $ft${"type":"object","properties":{"apenas_abertos":{"type":"boolean","description":"true (recomendado) = so pendentes e aprovados; false = ultimos 25 de qualquer situacao."}}}$ft$::jsonb, $ft$Citar card PENDENTE devolvido aqui NAO e fabricar ato. Se um pedido nao aparece, ele NAO existe. Leia o campo estado: executado significa que o objeto existe e id_criado_na_meta traz o id; execucao_falhou significa que terminou e falhou. A EXECUCAO E SINCRONA COM A APROVACAO: PROIBIDO responder 'aguarde alguns instantes'. destino_url e o link do CRIATIVO no card (wa.me em trafego WEBSITE); o conjunto guarda so o tipo, entao para comparar o link do anuncio com o do conjunto confronte destino_url do card com o wa.me definido para aquele CONJ.0N nesta conversa.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$get_campaign_detail$ft$, $ft$Detalhe e serie diaria de UMA campanha (name_like OU campaign_id da Meta), com totais do periodo e special_ad_categories da CAMPANHA. Passe date_from/date_to quando o gestor der a janela. NAO substitui get_detalhe_anuncios, que traz a serie por anuncio e por conjunto.$ft$, $ft${"type":"object","properties":{"name_like":{"type":"string"},"campaign_id":{"type":"string"},"date_from":{"type":"string"},"date_to":{"type":"string"}}}$ft$::jsonb, $ft$Cada dia e os totais trazem gasto, impressoes, alcance, frequencia, cliques_todos, cliques_no_link, visualizacoes_lp, formularios, conversas, CTR, CPC e CPM. Sao DUAS BASES DE CLIQUE e elas nunca se misturam. Dia sem linha significa que a coleta D-1 ainda nao chegou, nao entrega zero.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_conhecimento$ft$, $ft$BASE DE CONHECIMENTO TECNICA da casa: politica da Meta, compliance financeiro no Brasil, atlas de metricas, criacao e edicao de campanha/conjunto/anuncio, otimizacao e diagnostico, Marketing API e biblioteca de criativo. Use SEMPRE que a pergunta for conceitual, de politica, de metodo ou de definicao de metrica, e ao propor ou auditar criativo. Os temas validos estao no seu contexto; para anuncio financeiro e categoria especial o tema e 'compliance'.$ft$, $ft${"type":"object","properties":{"tema":{"type":"string","description":"o tema exato, conforme a lista no seu contexto"},"secao":{"type":"string","description":"opcional: titulo (ou parte) de uma secao especifica do tema"}},"required":["tema"]}$ft$::jsonb, $ft$Se o tema for extenso, o retorno vem parcial com o indice das secoes: chame de novo com o parametro 'secao' para ler o resto e nao conclua que o assunto nao esta coberto. Tema marcado como VENCIDO pode ser citado como referencia, mas declare ao gestor que precisa ser reverificado na fonte oficial antes de virar decisao.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_criativos_conteudo$ft$, $ft$CONTEUDO REAL DOS ANUNCIOS JA NO AR, coletado pelo sync: legenda, titulo, CTA, se tem imagem, gasto acumulado, formularios, status, destino_url (link do CTA do criativo) e destino (whatsapp quando wa.me ou api.whatsapp, senao site). Use para qualquer pergunta sobre o que os anuncios dizem e para auditar compliance das pecas EM OPERACAO, passando a legenda daqui para check_compliance. Para achar UM anuncio especifico use busca_nome em vez de folhear a lista. NAO serve para escolher peca do acervo: isso e get_acervo_para_anuncio.$ft$, $ft${"type":"object","properties":{"somente_ativas":{"type":"boolean","description":"true (recomendado) = so criativos em campanha ativa; false = historico operacional (PAUSED/CAMPAIGN_PAUSED), payload maior. Com busca_nome o default ja e false."},"busca_nome":{"type":"string","description":"Parte do nome do anuncio. Casa por pedaco e ignora maiusculas: 'reel02' acha 'AD_LPV2_A1_Reel02'."},"pagina":{"type":"integer","description":"So com busca_nome. Comeca em 1, 20 itens por pagina; leia 'restantes'."}}}$ft$::jsonb, $ft$O NUMERO DE WHATSAPP DE DESTINO de cada peca sai daqui (ex.: wa.me/5571993451315): e CONFIG do criativo coletada do Pipeboard, nao a analitica de conversa WABA pos-clique, que esta congelada — o destino E legivel e voce DEVE informa-lo quando perguntado. DELETED e ARCHIVED nunca entram, mesmo com somente_ativas=false, porque sairam da memoria operacional; CAMPAIGN_PAUSED continua (existe, nao entrega). Pode vir truncado: leia exibidos, omitidos e aviso_corte e nunca trate item omitido como inexistente — sao 67 anuncios e ja houve anuncio existente dado por inexistente por estar no pedaco omitido. Com busca_nome o retorno traz total_que_casam_com_a_busca, e SO se ele for zero o anuncio realmente nao existe; a busca casa por pedaco e ignora maiusculas, e e o caminho certo para achar o MOLDE antes de propor criar_anuncio_a_partir_de. Sem busca_nome vem a listagem paginada com legendas_unicas, o dedupe para auditoria de compliance do acervo.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_detalhe_anuncios$ft$, $ft$DETALHE POR ANUNCIO E POR CONJUNTO de UMA campanha: status, destino, CTA, totais da janela e serie diaria (gasto, impressoes, alcance, cliques, CTR, CPC, CPM, formularios, conversas). Aceita campaign_id (ID Meta) OU name_like; para 2 campanhas, chame 2 vezes. PAGINADO em 6 anuncios por pagina com serie: se restantes>0, pagine. PROIBIDO dizer que o detalhamento por anuncio 'nao foi retornado nesta rodada' sem ter chamado isto.$ft$, $ft${"type":"object","properties":{"campaign_id":{"type":"string","description":"ID Meta da campanha (external_id)."},"name_like":{"type":"string","description":"Trecho do nome da campanha, se não tiver o ID."},"date_from":{"type":"string","description":"YYYY-MM-DD"},"date_to":{"type":"string","description":"YYYY-MM-DD"},"pagina":{"type":"number","description":"Página de anúncios, começando em 1."},"incluir_serie_diaria":{"type":"boolean","description":"Default true. false devolve mais anúncios sem a série."}}}$ft$::jsonb, $ft$DELETED e ARCHIVED NAO entram em total_anuncios nem na lista: PROIBIDO cita-los como 'anuncios registrados'. CAMPAIGN_PAUSED continua no inventario — o objeto EXISTE e so nao entrega porque a campanha-mae esta pausada. Conjunto ACTIVE com anuncios=0 e zero pecas operacionais naquele conjunto, nao 'N registrados exclusos'. Somar as duas coisas foi o erro de 02/09/2026 na VISTTA: 29 exclusos mais 11 pausados pela campanha viraram '40 anuncios'.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_drive_criativos$ft$, $ft$INVENTARIO DA PASTA DE CRIATIVOS NOVOS no Google Drive (somente leitura): caminho, nome, tipo e data, sem thumbnail. Recorte com meio (la_felicita|juridico|sistema_ocular) e formatos (Reels, Videos). Use para LISTAR o que existe na pasta; nao substitui por get_criativos_conteudo, que traz anuncios ja no ar.$ft$, $ft${"type":"object","properties":{"meio":{"type":"string","enum":["la_felicita","juridico","sistema_ocular"]},"formatos":{"type":"array","items":{"type":"string"}}}}$ft$::jsonb, $ft$Nao le o conteudo interno do video: a leitura e por nome e caminho. Pode vir truncado — leia aviso_corte e nunca trate item omitido como inexistente. RECORTE DE FORMATO SO QUANDO O GESTOR RESTRINGIR: retorno com 0 arquivos quase sempre e recorte errado, nao pasta vazia — o Juridico e a pasta 'COHAPM Juridico - Exports Finais' e NAO tem subpasta Reels/Videos, entao formatos=[Reels,Videos] ali devolve lista vazia com 42 videos existentes (02/09/2026). Se voltar zero, releia NA MESMA RODADA sem formatos e sem produto. Pedido de La Felicita recorta meio=la_felicita e as pastas Reels/Videos. As pastas monitoradas estao no banco: PROIBIDO perguntar ao gestor o nome ou o caminho da pasta.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_estrutura_conjuntos$ft$, $ft$ESTRUTURA DOS CONJUNTOS desta empresa: nome, status, campanha_status, entregando (true so se conjunto E campanha estao ACTIVE), estrategia de lance, orcamento, segmentacao, gasto e destination_type (WEBSITE vs WHATSAPP). PAGINADO de 20: use a pagina seguinte enquanto restantes for maior que zero.$ft$, $ft${"type":"object","properties":{"pagina":{"type":"number","description":"Pagina, comecando em 1. Use a seguinte enquanto 'restantes' for maior que zero."}}}$ft$::jsonb, $ft$destination_type NAO e o wa.me: conjunto WEBSITE nao guarda o link — o wa.me fica no CRIATIVO (get_aprovacoes.destino_url ou get_criativos_conteudo). pegada/destino e numeros_whatsapp sao o DESTINO Click-to-WA do criativo, NAO inventario WABA; para numeros operacionais use get_waba_status. Conjunto ACTIVE sob campanha PAUSED tem entregando=false, isto e, nao esta no ar. DELETED e ARCHIVED, de conjunto e de anuncio, ficam de fora. Para criar_anuncio, o CONJ.N no NOME basta (CONJ.1_LAF_... = CONJ.1; barra ou nao e CONJ.1 vs CONJ.01 sao o mesmo numero): PROIBIDO pedir ao gestor o ID numerico da Meta, e CONJ.1 nunca e o CONJ.4 mais novo da mesma linha.$ft$, array['chat','job']::text[], $ft${"job":["pagina"]}$ft$::jsonb),
  ($ft$get_funil_credito$ft$, $ft$FORA DE ESCOPO desde 28/07/2026: CRM e conversao final foram removidos do sistema por decisao da empresa. Existe so por compatibilidade e devolve um aviso de fora-de-escopo. NAO a chame; se o gestor pedir proposta, contrato ou receita, explique a exclusao e ofereca as metricas de midia.$ft$, $ft${"type":"object","properties":{"dias":{"type":"number","description":"janela em dias (default 90). Use a MESMA janela do get_funnel ao comparar."}}}$ft$::jsonb, null, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$get_funnel$ft$, $ft$Funil de MIDIA num periodo, com cobertura_real (dias efetivamente com dado). Nao contem proposta nem contrato.$ft$, $ft${"type":"object","properties":{"date_from":{"type":"string"},"date_to":{"type":"string"}}}$ft$::jsonb, null, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_instagram_dos_anuncios$ft$, $ft$LEITURA AO VIVO na Graph: o Instagram de CADA anuncio da campanha (conjuntos ACTIVE e PAUSED), com handle quando a Meta expoe, id e classificacao coop_cohapm|cohapm|outro|sem_vinculo|id_sem_handle. Chame antes de afirmar vinculo ou de emitir alteracao.$ft$, $ft${"type":"object","properties":{"campanha":{"type":"string","description":"Nome da campanha (ex.: COHAPM_LAFELICITA_CONV_AGO26)."}},"required":["campanha"]}$ft$::jsonb, $ft$NAO presuma pelo perfil unico da conta e nao use so get_criativos_conteudo. Cobre a campanha La Felicita em trabalho (COHAPM_LAFELICITA_CONV_*); Juridico e SALT ficam de fora. Para ALTERAR, chame vincular_instagram_dos_anuncios na MESMA campanha.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$get_legendas_da_conversa$ft$, $ft$MEMORIA DURAVEL das legendas desta conversa (conversation_legendas): devolve o texto INTEGRAL por peca_chave ou drive_file_id. OBRIGATORIO chamar ANTES de dizer que uma legenda 'nao existe' ou que o 'texto integral nao esta disponivel', e antes de pedir ao gestor para colar copy.$ft$, $ft${"type":"object","properties":{"peca_chave":{"type":"string"},"drive_file_id":{"type":"string"}}}$ft$::jsonb, $ft$Se a peca esta aqui, use o texto: nunca invente amnesia. O store e o historico sao a memoria. Em 20/08/2026 o agente gerou 5 legendas de impulsao e depois pediu ao gestor para colar 3 de novo porque o corte de historico levou o final do slate — isso e proibido.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$get_meta_dicas$ft$, $ft$Dicas da Meta (Opportunity Score + campo classico recommendations), com first_seen_on/last_seen_on e veredito interno (concorda|discorda|nao_aplicavel|sem_regua).$ft$, $ft${"type":"object","properties":{"dias":{"type":"integer","description":"Janela em dias (default 14)."},"veredito":{"type":"string","description":"Filtro opcional: concorda|discorda|nao_aplicavel|sem_regua"}}}$ft$::jsonb, $ft$E PROIBIDO repetir a dica da Meta como se fosse nossa: cite sempre o veredito interno. A API pode listar MENOS itens que o badge do Ads Manager; se vier vazio apos sync e o gestor apontar badge na UI, diga a assimetria documentada pela Meta e nao invente o texto da dica. 20/08/2026: nao abra listar_ferramentas_pipeboard nem ler_pipeboard para essa pergunta, era o padrao que estourava 150s em pergunta simples.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_overview$ft$, $ft$Visao geral de MIDIA: campanhas ativas (status real da Meta), gasto e resultados dos ultimos 7 dias, com dias_com_dado para checar cobertura.$ft$, $ft${"type":"object","properties":{}}$ft$::jsonb, null, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_recommendations$ft$, $ft$FILA INTERNA de custo de midia (ai_recommendations, regua nossa). NAO e o badge do Ads Manager nem Opportunity Score — para dicas da Meta use get_meta_dicas.$ft$, $ft${"type":"object","properties":{}}$ft$::jsonb, null, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_slate_da_conversa$ft$, $ft$MEMORIA DURAVEL do SLATE desta conversa (conversation_slate): as pecas JA escolhidas, por CONJ.N, com nome, drive_file_id, angulo e CTA. OBRIGATORIO antes de dizer que 'o acervo nao traz o slate' ou de pedir ao gestor para re-colar as pecas.$ft$, $ft${"type":"object","properties":{"conjunto":{"type":"number","description":"Opcional: so pecas deste CONJ.N."}}}$ft$::jsonb, $ft$Inventario do Drive (N videos da pasta) NAO e o slate e nao apaga a selecao. Pedido de legendas ou cards dos videos que VOCE selecionou: leia daqui e chame gerar_legendas por peca. O store sobrevive ao corte de historico, entao ausencia no historico nao prova ausencia de slate.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$get_waba_status$ft$, $ft$INVENTARIO WHATSAPP da empresa. Obrigatorio para pergunta sobre numero operacional ou de pe, qual WA linkar, WABA, Cloud, qualidade ou tier, e para o isolamento Juridico vs La Felicita. Filtro meio=juridico|la_felicita|financeiro|outro. NAO decide se um conjunto CTWA pode ser emitido: isso e get_whatsapp_da_pagina.$ft$, $ft${"type":"object","properties":{"meio":{"type":"string","description":"Opcional: juridico | la_felicita | financeiro | outro"}}}$ft$::jsonb, $ft$Devolve DUAS listas que nunca se misturam: waba_cloud_on_premise (CLOUD_API + ON_PREMISE; de_pe so quando CONNECTED, com qualidade e tier) e click_to_whatsapp_inventario (destino wa.me; de_pe so quando IN_ACTIVE_ADS). NUNCA trate CTWA IN_ADS como numero de pe nem peca ao gestor para escolher so entre os CTWA se a lista WABA veio no retorno. get_estrutura_conjuntos e get_criativos_conteudo mostram apenas o destino wa.me do anuncio e NAO substituem esta leitura. COHAPM: isole Juridico e La Felicita.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_waba_template_insights$ft$, $ft$Insights por TEMPLATE de WhatsApp numa janela: envios, entregues, leituras, cliques e taxa de clique.$ft$, $ft${"type":"object","properties":{"days":{"type":"number","description":"janela em dias (default 30)"}}}$ft$::jsonb, $ft$Detalhe por numero ainda nao e coletado, e o retorno declara isso.$ft$, array['job']::text[], $ft${}$ft$::jsonb),
  ($ft$get_whatsapp_da_pagina$ft$, $ft$CHECAGEM antes de emitir conjunto CTWA: diz se o numero e ativo WhatsApp da conta, olhando Pagina, WABAs do Business e conjuntos existentes. Distinto de get_waba_status, que e inventario. Escrita continua sendo propose_action.$ft$, $ft${"type":"object","properties":{"numero":{"type":"string","description":"Telefone do conjunto (com ou sem o 9 extra)."}}}$ft$::jsonb, $ft$EMITA criar_conjunto_a_partir_de com destination_type=WHATSAPP nos DOIS casos: e_ativo_whatsapp_da_conta/casou_na_api false e apenas inventario, NAO impedimento, porque o create sai pelo driver pipeboard, que cria numero ligado so a Pagina. Medido em 01/09/2026 com o mesmo promoted_object e o mesmo destination_type: o driver graph deu HTTP 400 / 1487246 as 11:49 UTC e o driver pipeboard criou o conjunto 120249829825270182 as 12:46 UTC. Os numeros VISTTA 7199189-4229, 7199185-8107, 7199264-9576 e 7199188-7731 nao estao em WABA alguma e o Pipeboard cria assim mesmo. PROIBIDO dizer que falta vincular o numero a uma WABA, que o numero nao existe, que nao esta no seletor da Pagina ou que so o Gerenciador cria — a medicao desmentiu tudo isso. PROIBIDO trocar por numero Juridico ou La Felicita em campanha VISTTA.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$ler_brand_identity$ft$, $ft$ESP-36: identidade de marca VIGENTE. COHAPM tem TRES vozes: meio=juridico | la_felicita | sistema_ocular (VISTTA). Sem meio, a RPC prefere juridico.$ft$, $ft${"type":"object","properties":{"meio":{"type":"string","enum":["la_felicita","juridico","sistema_ocular"],"description":"Recorte de voz. Obrigatorio em COHAPM quando o pedido recorta um empreendimento."}}}$ft$::jsonb, $ft$NUNCA use copy Juridico nas outras linhas. Campanha ou produto La Felicita/imovel: meio=la_felicita. Sistema Ocular/VISTTA: meio=sistema_ocular. gerar_legendas consome a identidade automaticamente quando produto e meio vem certos.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$ler_entregas_digest$ft$, $ft$ESP-41: config de digest (cadencia, slots, e-mails, alerta critico) e entregas recentes com status por entrega. Use em 'o relatorio de hoje foi enviado?', 'chega por e-mail?', 'qual o horario do digest'.$ft$, $ft${"type":"object","properties":{"dias":{"type":"integer","description":"Janela em dias (default 7)."}}}$ft$::jsonb, $ft$Leitura pura do que a edge enviar-digest e o trigger gravaram. status sem_provedor = falta configurar e-mail; sem_destinatario = sem e-mail cadastrado. Nos dois casos o digest segue no chat.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$ler_perfil_vencedor$ft$, $ft$ESP-34: le a ultima versao (ou uma versao especifica) do perfil do vencedor ja computado, com vencedores, padroes agregados, criterio, procedencia e lacunas. Leitura pura: nao recalcula.$ft$, $ft${"type":"object","properties":{"versao":{"type":"integer","description":"Versao especifica; se ausente, retorna a mais recente."}}}$ft$::jsonb, $ft$Se nunca foi computado, o retorno avisa para chamar computar_perfil_vencedor.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$ler_pipeboard$ft$, $ft$Leitura AO VIVO do Pipeboard na conta Meta desta empresa. Use quando faltar dado que o banco nao cobre: config fresca do dia, breakdown, activities, pages, pixels, audiences, insight pontual.$ft$, $ft${"type":"object","properties":{"ferramenta":{"type":"string","description":"Nome exato da tool Pipeboard de leitura (ex.: get_campaign_details)."},"argumentos":{"type":"object","description":"Argumentos da tool (account_id e injetado se a empresa tiver uma unica conta)."}},"required":["ferramenta"]}$ft$::jsonb, $ft$Prefira as tools de DB (get_overview, get_campaign_detail, get_estrutura_conjuntos, get_criativos_conteudo, funil e ranking) quando bastarem. SO leitura: create, update, delete e upload sao recusados, e contas fora da empresa tambem. A resposta pode vir truncada (aviso_corte).$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$listar_ferramentas_pipeboard$ft$, $ft$Catalogo ao vivo das ferramentas de LEITURA do Pipeboard. Use quando nao souber qual endpoint traz um dado que as leituras de banco nao cobrem; depois chame ler_pipeboard com o nome exato.$ft$, $ft${"type":"object","properties":{}}$ft$::jsonb, null, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$nota_visual_da_peca$ft$, $ft$Nota visual textual completa de UMA peca do Drive: revisao aberta, base, produto, aproveitabilidade, risco, motivo e divergencia de produto. Chame com o drive_file_id atual (vem de get_acervo_para_anuncio ou get_analise_visual_drive) antes de recomendar, classificar ou listar a peca como candidata.$ft$, $ft${"type":"object","properties":{"drive_file_id":{"type":"string"}},"required":["drive_file_id"]}$ft$::jsonb, $ft$Ausencia de leitura nao e ausencia de risco: a nota informa, nao substitui decisao e nao e veredito de compliance. get_analise_visual_drive serve para inventario e triagem e nao autoriza repetir classificacao antiga. Se nao houver espaco para ler as notas das candidatas, nao recomende nenhuma pelo nome. Nunca recomende o video 19 sem sua nota vigente, que declara aparencia de credito empresarial e incerteza.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$origem_drive_dos_anuncios$ft$, $ft$PASTA DO DRIVE DE CADA ANUNCIO JA NO AR de um conjunto ou campanha. UMA chamada lista todos: nome, pasta, peca_nome, drive_file_id e vinculo. OBRIGATORIA quando o gestor pergunta de qual pasta do Drive sao os anuncios do CONJ.N. NAO e inventario de pecas novas (isso e get_acervo_para_anuncio), e NAO declare 'sem vinculo' sem ter chamado isto.$ft$, $ft${"type":"object","properties":{"conjunto":{"type":"number","description":"Numero do conjunto (1-99). Preferivel."},"name_like":{"type":"string","description":"Trecho da campanha (ex.: VISTTA_CONV_WA_SET26) se houver mais de um CONJ.N."},"campaign_id":{"type":"string","description":"ID Meta da campanha."},"ad_external_id":{"type":"string","description":"Se quiser um anuncio so."},"incluir_apagados":{"type":"boolean","description":"Default false. DELETED/ARCHIVED ficam de fora."}}}$ft$::jsonb, $ft$A fonte do vinculo e o card criar_anuncio_a_partir_de, com drive_file_id e pasta da peca: PROIBIDO deduzir 2.mp4 a partir de AD_..._2. Escreva pasta, peca_nome e drive_file_id de CADA anuncio e NUNCA declare 'sem vinculo' quando a tool trouxe o id — em 02/09/2026, 5 de 6 anuncios do VISTTA sairam como 'sem vinculo' com os cards tendo pasta e drive_file_id. casar_criativo_performance e plano B: nele passe SO ad_external_id e nunca invente drive_file_id. Ambiguidade de CONJ.N em duas campanhas se resolve pelo name_like da campanha do fio, nao perguntando ao gestor.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$panorama_utm_anuncios$ft$, $ft$Coleta de url_tags e destino dos anuncios: nunca lido, lido sem/com rotulo, rotulos, ambiguidades e URLs. Chame antes de dizer se um teste A/B/C, variante ou rastreio e legivel, ou se existe vencedora.$ft$, $ft${"type":"object","properties":{}}$ft$::jsonb, $ft$Distingue ausencia configurada de nao coleta apenas quando o retorno permite. NAO mede desempenho nem leads por UTM, e o token alcanca so parte das contas. Sem desempenho por rotulo, nao invente vencedor: campanha vazia e causa possivel, mas nao substitui a leitura dos rotulos.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$pode_pausar_por_custo$ft$, $ft$Verifica se um anuncio pode ser AVALIADO para pausa por custo: libera quando maduro, ou pela excecao dura de zero resultado com CTR baixo e piso de gasto. Exige ad_external_id.$ft$, $ft${"type":"object","properties":{"ad_external_id":{"type":"string"}},"required":["ad_external_id"]}$ft$::jsonb, $ft$Nao verifica a guarda do unico conjunto ou alternativa ativa: permitido aqui NAO significa seguro pausar — cruze com decidir_sobre_conjunto. Julgar e aqui; emitir o card e ato do Executor.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$propose_action$ft$, $ft$Cria PEDIDO DE APROVACAO (ActionCard) para todo ato na conta Meta. NAO executa: o card fica PENDENTE, so um administrador aprova, e expira em 24h. SO use quando o gestor pedir o ato com verbo explicito (emitir, criar, subir, pausar, ativar, escalar, duplicar, renomear, alterar, vincular). PERGUNTA sem verbo de ato — inclusive 'antes da aprovacao' e 'o anuncio esta com o mesmo link' — se responde com get_aprovacoes, get_estrutura_conjuntos ou get_criativos_conteudo, NAO com esta tool. Exige justificativa, metrica_sucesso e reversa. target_name e o nome ATUAL do objeto; quando o nome nao for unico, mande params.alvo_external_id com o id da Meta. EXCLUIR nao existe em nenhum nivel: para tirar do ar use pausar_*. Sem approval_id no retorno, o card NAO existe.$ft$, $ft${"type":"object","properties":{"action_type":{"type":"string","enum":["pausar_criativo","ativar_criativo","escalar_criativo","pausar_campanha","ativar_campanha","pausar_conjunto","ativar_conjunto","alterar_orcamento","renomear_campanha","renomear_conjunto","renomear_criativo","alterar_categoria_especial_campanha","ajustar_posicionamentos_do_conjunto","vincular_instagram_dos_anuncios","criar_campanha","criar_conjunto_a_partir_de","criar_anuncio_a_partir_de","escalar_duplicar"]},"target_name":{"type":"string"},"justificativa":{"type":"string"},"mecanismo":{"type":"string"},"metrica_sucesso":{"type":"string"},"janela_leitura":{"type":"string"},"reversa":{"type":"string"},"risco":{"type":"string"},"params":{"type":"object","description":"Campos da acao. alvo_external_id: id da Meta do objeto alvo, quando o nome nao for unico. Nome livre em nome / nome_novo / novo_nome. GEO: params.bairros ou params.geo_locations, com as keys de buscar_geolocalizacao."}},"required":["action_type","target_name","justificativa","metrica_sucesso","reversa"]}$ft$::jsonb, $ft$NOMENCLATURA: nome livre ja falado nesta conversa E contrato — params.nome_novo recebe o string EXATO (ex. JUR_CONV_CONJ03_AD01_...). PROIBIDO trocar por [MARCA][CANAL][WA][LEADS]; o padrao estruturado so vale se NINGUEM falou nome, e nunca passe placeholder 'composto'.
CRIACAO: criar_campanha, criar_conjunto_a_partir_de, criar_anuncio_a_partir_de e escalar_duplicar nascem ACTIVE na aprovacao. Molde e OPCIONAL: target_name='sem_molde' vale em QUALQUER familia, inclusive trafego/website. PROIBIDO recusar criar_conjunto por falta de molde. Molde OFFSITE_CONVERSIONS e aceito em engajamento: o executor descarta os campos de conversao e grava POST_ENGAGEMENT + page_id. Peca nova de anuncio: sem_molde=true + drive_file_id do acervo.
CARROSSEL esta HABILITADO na Meta: params.child_attachments recebe de 2 a 10 slides, cada um com seu image_hash, e cada slide passa por upload_midia antes — nao diga que carrossel so entra como imagem estatica.
criar_anuncio: o Instagram vem auto-preenchido da meta_execution_config e a emissao recusa com instagram_nao_vinculado se a config nao tiver id — nunca emita peca que o gestor precise vincular a mao. WEBSITE + LANDING_PAGE_VIEWS nao carrega canal WA nem objetivo LEADS.
escalar_duplicar (ESP-25/39): target_name e o conjunto a escalar; so emite se avaliar_escala.apto_a_escalar; orcamento travado em +20% pela RPC; nao fica em campanha TESTE (se o molde esta em TESTE, informe params.campanha_destino de uma campanha ESCALA); targeting herdado; nao edita o original; anuncios nao sao copiados neste card.
ajustar_posicionamentos_do_conjunto e acao CORRETIVA de conjunto antigo ou de teste: target_name e o conjunto e params.formato_midia e obrigatorio (video|imagem). VIDEO aplica o padrao manual observado nos 3 conjuntos de video ACTIVE (publisher_platforms=[facebook] + 8 facebook_positions, sem facebook.right_hand_column); IMAGEM nao exclui nada.
pausar_conjunto: target_name e o ad set, e a guarda do unico conjunto entregando bloqueia o card se pausar este zerar a entrega (decidir_sobre_conjunto).
GEO opcional: params.bairros (keys Meta) ou params.geo_locations, resolvidos por buscar_geolocalizacao em lotes de 40.
COHAPM, ERRO GRAVE e nao aviso: peca La Felicita (_LAF_, CONJ.1_LAF, FELICITA) NUNCA em campanha ou conjunto JURIDICO, e peca Juridico NUNCA em LAFELICITA — o sistema RECUSA o card. params.conjunto_destino e o NOME com CONJ.N (CONJ.1_LAF_..., CONJ.1, CONJ.01): PROIBIDO pedir o ID numerico da Meta, e CONJ.1 nunca e o CONJ.4 mais novo da mesma linha.
A escrita so ocorre depois da aprovacao e e relida e reconciliada pela Graph.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$registrar_legenda_da_conversa$ft$, $ft$Grava ou atualiza UMA legenda no store duravel desta conversa. Use quando propuser copy no chat SEM passar por gerar_legendas (ex.: slate de impulsao com legenda editorial) ou para marcar a variante escolhida pelo gestor. peca_chave estavel (carrossel_2, card_capa_1) + legenda integral, com drive_file_id quando houver.$ft$, $ft${"type":"object","properties":{"peca_chave":{"type":"string"},"legenda":{"type":"string"},"drive_file_id":{"type":"string"},"variante_indice":{"type":"number"},"selecionada":{"type":"boolean"},"objetivo":{"type":"string"}},"required":["peca_chave","legenda"]}$ft$::jsonb, null, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$registrar_peca_da_conversa$ft$, $ft$Grava UMA peca no slate duravel (conjunto + drive_file_id + nome). Use ao selecionar peca nova que deva persistir na hora; o sistema tambem extrai tabelas CONJ.N da propria conversa.$ft$, $ft${"type":"object","properties":{"conjunto":{"type":"number"},"drive_file_id":{"type":"string"},"nome":{"type":"string"},"pasta":{"type":"string"},"angulo":{"type":"string"},"cta":{"type":"string"},"peca_chave":{"type":"string"}},"required":["conjunto","drive_file_id","nome"]}$ft$::jsonb, null, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$registrar_veredito_peca_em_revisao$ft$, $ft$PROPOE veredito de compliance de uma peca em revisao emitindo um CARD DE APROVACAO. Valores: liberado_como_esta (se aprovado, desliga bloqueia_uso), ajustar_peca ou nao_usar (mantem o bloqueio).$ft$, $ft${"type":"object","properties":{"drive_file_id":{"type":"string"},"veredito":{"type":"string","enum":["liberado_como_esta","ajustar_peca","nao_usar"]},"veredito_por":{"type":"string","description":"Opcional: quem pediu o veredito (ex.: Roberto). Registro informativo, NAO assinatura."},"nota":{"type":"string","description":"Opcional: condicao ou justificativa que acompanha a proposta."}},"required":["drive_file_id","veredito"]}$ft$::jsonb, $ft$Voce PROPOE, nao decide: a peca continua impedida ate um administrador aprovar o card na tela. A assinatura gravada e a de QUEM APROVAR, resolvida por auth.users — veredito_por entra apenas como autor_sugerido e nao tem valor de decisao. Havendo proposta pendente para a peca, a chamada e recusada. Ao responder, diga que emitiu proposta e que a decisao e do responsavel; nunca diga que liberou a peca. Nunca faca UPDATE a mao: em 10/08/2026 um subagente escreveu veredito direto assinando com o nome do fundador e liberou 5 pecas do FIN-04 sem decisao dele, e foi por isso que essa porta foi fechada.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$renomear_campanha$ft$, $ft$Emite CARD DE APROVACAO para renomear campanha existente, pelo update_campaign nativo do Pipeboard. NOME LIVRE: passe novo_nome com a string que o gestor quiser. Localiza a campanha pelo nome atual; ambiguidade exige o nome completo.$ft$, $ft${"type":"object","properties":{"campanha_atual":{"type":"string"},"novo_nome":{"type":"string","description":"Nome livre desejado (prioridade)."},"marca":{"type":"string"},"canal":{"type":"string"},"objetivo_tag":{"type":"string"},"produto":{"type":"string"},"papel":{"type":"string","description":"TESTE ou ESCALA (opcional, so para sugestao estruturada)"},"rotulo":{"type":"string"},"periodo":{"type":"string"},"justificativa":{"type":"string"}},"required":["campanha_atual","novo_nome"]}$ft$::jsonb, $ft$NAO altera nada antes da aprovacao. O padrao [MARCA][CANAL][OBJ] e apenas sugestao opcional: marca, canal, objetivo_tag, papel, rotulo e periodo so entram se o gestor quiser a sugestao estruturada. Ao aprovar, meta-actions exige Pipeboard, envia somente campaign_id e name, e reconcilia pela Graph.$ft$, array['chat']::text[], $ft${}$ft$::jsonb),
  ($ft$saude_das_integracoes$ft$, $ft$Saude das integracoes Meta desta empresa por evidencia de ads, snapshots, breakdown e tres relogios.$ft$, $ft${"type":"object","properties":{"dias_tolerancia":{"type":"integer","description":"Opcional; padrao da RPC = 3 dias."}}}$ft$::jsonb, $ft$Declara divergencias contra status/estado_operacional sem alterar nenhum deles. Nao promete diagnosticar provedores fora do que o retorno traz.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$saude_dos_tokens$ft$, $ft$ESP-30: saude dos tokens Meta (ads/waba) por METADADO gravado em meta_tokens: dias para expirar, dias para o fim do data_access, escopos faltando vs o esperado do papel e veredito (ok|expira_em_breve|expirado|data_access_expirado|escopo_incompleto|invalido). Use em 'o token vai vencer?', 'temos permissao pra X?', 'por que parou de coletar'.$ft$, $ft${"type":"object","properties":{}}$ft$::jsonb, $ft$Leitura pura do ultimo estado do meta-token-monitor: NAO chama a Graph e NUNCA expoe o valor do token. Complementa saude_das_integracoes (entrega) e bm-monitor (status e cobranca da conta).$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$score_de_prontidao$ft$, $ft$ESP-38: score 0-100 de prontidao da empresa para propor e executar anuncios, somando config de execucao (25), integracao Meta viva (25), postura de criacao (20), brand_identity (15), destino_por_produto (10) e driver resolvivel (5). Use em 'estamos prontos?', 'por que nao consigo criar anuncio?', 'o que falta'.$ft$, $ft${"type":"object","properties":{}}$ft$::jsonb, $ft$Devolve nivel (bloqueado|parcial|operacional|pronto), checks itemizados com evidencia e lacuna, bloqueios duros e recomendacoes. Read-only: NAO altera nada e NAO substitui os gates por pedido (validar_pedido_contra_contrato / pedido_de_anuncio_completo).$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$teto_vigente$ft$, $ft$FONTE PRIORITARIA do teto vigente de uma metrica (ex.: custo_por_formulario, custo_por_conversa, custo_por_lead_lp). Devolve qual regua governa, valor, denominador, autor/data/citacao da meta de negocio, consistencia historica e divergencias.$ft$, $ft${"type":"object","properties":{"metric":{"type":"string","description":"Metrica exata, por exemplo custo_por_formulario, custo_por_conversa ou custo_por_lead_lp."}},"required":["metric"]}$ft$::jsonb, $ft$Use SOMENTE a regua que o retorno disser que governa e cite autor/data quando houver meta de negocio; declare divergencias e avisos. Nunca leia a tabela targets direto: isolada, ela NAO decide teto vigente. Consistencia historica NAO e veredito de negocio.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$upload_midia$ft$, $ft$Sobe UMA peca do Drive (imagem ou video) para a biblioteca da conta Meta e grava meta_image_hash ou meta_video_id. Use quando na_biblioteca_da_meta=false. NAO cria anuncio. Teto de arquivo = o da Meta: video ate 4 GB, imagem ate 8 MB — NAO recuse video entre 50 MB e 4 GB.$ft$, $ft${"type":"object","properties":{"drive_file_id":{"type":"string","description":"Id do arquivo no Drive (vem de get_acervo_para_anuncio)."},"account_id":{"type":"string","description":"Opcional; default = unica conta permitida da empresa."}},"required":["drive_file_id"]}$ft$::jsonb, $ft$Idempotente: peca ja enviada devolve o id sem reenviar. Envio em partes — se vier em_andamento, chame de novo com o MESMO drive_file_id. Video so vira card com pronto=true. LOTE: se o gestor pedir para subir os restantes ou faltantes, chame upload_midia para CADA peca ainda fora, varias na mesma rodada; NAO invente teto de 5 acoes por hora e nao pare no quinto por conta propria, so pare se a ferramenta recusar por teto horario de verdade. NAO peca ao gestor para repetir 'suba os restantes'. O retorno traz o nome: liste o NOME de cada peca enviada, em andamento e ainda fora. Peca off-brand so entra se o gestor pedir aquela peca.$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$validar_pedido_contra_contrato$ft$, $ft$Valida um pedido (json) contra o contrato declarado em contrato_de_execucao para a acao (criar_anuncio_a_partir_de, criar_conjunto_a_partir_de, criar_campanha...).$ft$, $ft${"type":"object","properties":{"acao":{"type":"string","description":"Ex.: criar_anuncio_a_partir_de, criar_conjunto_a_partir_de, criar_campanha."},"pedido":{"type":"object","description":"Objeto com os campos do payload que o executor leria."}},"required":["acao","pedido"]}$ft$::jsonb, $ft$Sem linhas vigentes para a acao devolve valido=false com motivo contrato_desconhecido — nao inventa campos. Falta de obrigatorio recusa com faltando[]; campos extras NAO invalidam e vao em nao_previstos_no_contrato para decisao humana. O contrato de criar_anuncio_a_partir_de e o MESMO vocabulario que pedido_de_anuncio_completo aceita: pedido valido aqui e entendido la, e vice-versa. LACUNAS HONESTAS: o contrato foi derivado do codigo montarCriacao (meta-actions), nao de card executado; url_tags e opcional e vai no adcreative, nao no ad; meta_video_id, legenda e thumbnail_url sao opcionais da rota peca nova; status_inicial e opcional porque o executor FORCA ACTIVE no body e nao le o payload. NAO substitui pedido_de_anuncio_completo (biblioteca, compliance, procedencia).$ft$, array['chat','job']::text[], $ft${}$ft$::jsonb),
  ($ft$vincular_instagram_dos_anuncios$ft$, $ft$Emite CARD DE APROVACAO para vincular o Instagram oficial @cohapm em TODOS os anuncios da campanha em trabalho que ainda nao o usam, conjuntos ativos e pausados. Le a Graph na hora da proposta.$ft$, $ft${"type":"object","properties":{"campanha":{"type":"string","description":"Nome da campanha (ex.: COHAPM_LAFELICITA_CONV_AGO26)."},"justificativa":{"type":"string"}},"required":["campanha"]}$ft$::jsonb, $ft$NAO executa na hora, NAO ativa conjunto pausado e NAO toca outras campanhas. A aprovacao gera um novo criativo e republica o anuncio com o mesmo status. PROIBIDO dizer que falta ferramenta de edicao de Instagram.$ft$, array['chat']::text[], $ft${}$ft$::jsonb)
on conflict (chave) do update set
  descricao           = excluded.descricao,
  parametros          = excluded.parametros,
  doutrina            = excluded.doutrina,
  superficies         = excluded.superficies,
  parametros_omitidos = excluded.parametros_omitidos,
  vigente             = true,
  atualizado_em       = now();

-- As duas ferramentas que existiam no codigo e nao no registro. Sem esta linha o
-- estreitamento por agente as removia do turno.
insert into public.agent_unidades (agent_codigo, tipo, chave, observacao) values
  ('AG-02', 'ferramenta', 'get_detalhe_anuncios', 'Serie diaria por anuncio e por conjunto'),
  ('AG-02', 'ferramenta', 'origem_drive_dos_anuncios', 'Pasta de origem das pecas ja no ar'),
  ('AG-03', 'ferramenta', 'origem_drive_dos_anuncios', 'Lado Drive do cruzamento peca x anuncio')
on conflict (agent_codigo, tipo, chave) do nothing;

-- Prompts dos agentes: mesmo corte, mesma razao.
--
-- papel, delegar_quando e nao_delegar_quando dos 7 agentes roteaveis somavam 5.791 chars, e
-- eles entram no prompt do Roteador em TODO turno (montarPromptDelegacao) mais no bloco de
-- identidade do turno (blocoIdentidadeAgentes). O que saiu foi enumeracao que o proprio
-- DELEGUE QUANDO ja cobre e repeticao do setor, que ja vai no cabecalho da linha. As
-- fronteiras negativas foram preservadas inteiras na condicao: elas sao o que impede o erro
-- de roteamento por semelhanca de termo, e cada uma nomeia o agente certo.
--
-- AG-00 e AG-01 ficaram como estao: roteavel=false, entao o texto deles nunca entra em prompt
-- nenhum. Encurtar ali nao economiza um token e so apagaria a documentacao do desenho.

update public.agents set papel = $ag$Responde POR QUE a conta entrega o que entrega: numero de midia, serie diaria por anuncio e por conjunto, custo contra o teto vigente, e a CONFIGURACAO que produz esse resultado (CBO vs ABO, orcamento por conjunto, lance, targeting, optimization_goal).$ag$,
  delegar_quando = $ag$Metrica, valor, periodo, comparacao entre campanhas ou anuncios, ranking por gasto/alcance/conversas, "esta caro", "caiu", "subiu", "vale escalar", "posso pausar", teto, meta, pacing, orcamento, CBO, ABO, lance, segmentacao, detalhamento ou serie diaria.$ag$,
  nao_delegar_quando = $ag$Conteudo da peca (o que a legenda diz, hook, CTA) e Estudio. Taxa de clique de TEMPLATE de WhatsApp e Mensageiro. Alerta ou recomendacao pendente e Sentinela. O ato de pausar ou escalar e Executor: o Analista julga, ele emite.$ag$
  where codigo = 'AG-02';

update public.agents set papel = $ag$Dono do ativo criativo no ciclo inteiro: a peca no acervo do Drive (inventario por pasta, formato e linha de produto), a leitura dos pixels (produto detectado, texto visivel, veredito), a peca ja no ar (legenda, titulo, CTA, destino) e a redacao da copy.$ag$,
  delegar_quando = $ag$Pasta do Drive, acervo, peca nova, video, reel, imagem, criativo, miniatura, "o que essa peca mostra", "classifique as pecas", "o que o anuncio diz", legenda, copy, texto, hook, headline, angulo, CTA, escrever ou reescrever legenda.$ag$,
  nao_delegar_quando = $ag$RESULTADO da peca em numeros (custo, CTR, ranking) e Analista. O veredito de conformidade e Guardiao: o Estudio escreve, ele aprova. Upload para a biblioteca da Meta e criacao de anuncio sao Executor.$ag$
  where codigo = 'AG-03';

update public.agents set papel = $ag$Unica autoridade sobre o que pode ir ao ar. Valida legenda e peca contra as regras versionadas (FIN, CRI, LGL), aplica as promessas proibidas com substituicao segura e bloqueia cruzamento de marca entre linhas de produto. O veredito e DETERMINISTICO pela severidade da regra, nunca pela opiniao do modelo.$ag$,
  delegar_quando = $ag$Compliance, conformidade, "pode anunciar isso", violacao, politica da Meta aplicada a um texto concreto, categoria especial, CET, credito, reprovacao, apelacao, auditar as legendas que estao no ar. SEMPRE em cascata depois de o Estudio escrever copy nova.$ag$,
  nao_delegar_quando = $ag$Duvida conceitual sobre politica sem texto para validar e Bibliotecario. A correcao da copy e Estudio: o Guardiao reprova e sugere, ele reescreve.$ag$
  where codigo = 'AG-04';

update public.agents set papel = $ag$Responde pelo destino da conversa: inventario WhatsApp separando WABA Cloud e ON_PREMISE (de pe = CONNECTED) do inventario Click-to-WhatsApp (de pe so IN_ACTIVE_ADS), qualidade e tier dos numeros, checagem do numero antes de emitir conjunto CTWA, e os templates utilitarios com seus insights.$ag$,
  delegar_quando = $ag$WhatsApp, WABA, numero de pe, qual numero linkar, wa.me, CTWA, Click-to-WhatsApp, tier, qualidade do numero, template, ou taxa de clique DE TEMPLATE.$ag$,
  nao_delegar_quando = $ag$Taxa de clique de CAMPANHA ou de anuncio e Analista, mesmo quando o destino do anuncio e WhatsApp. A emissao do conjunto CTWA e Executor: o Mensageiro confere o numero, ele emite.$ag$
  where codigo = 'AG-05';

update public.agents set papel = $ag$Unico agente com direito de provocar escrita. Emite card de aprovacao, valida o pedido contra o contrato de execucao declarado, sobe midia para a biblioteca da Meta e acompanha o card ate a Meta confirmar. Nao decide MERITO: decide se o ato e formalmente possivel e o coloca na fila para decisao humana.$ag$,
  delegar_quando = $ag$VERBO DE ATO: criar, crie, suba, subir, lance, proponha, duplique, escale, pause, ative, altere, aumente, reduza, emita, replique, renomeie, vincule. Tambem o estado de um card, o que esta pendente de aprovacao, ou se algo ja foi criado.$ag$,
  nao_delegar_quando = $ag$Pergunta que so parece ato: "esse conjunto deveria ser pausado?" e julgamento do Analista. "Crie as legendas" tem verbo de ato, mas o ato e escrever copy, e isso e Estudio. O Executor nunca decide se o ato e uma boa ideia.$ag$
  where codigo = 'AG-06';

update public.agents set papel = $ag$Observa a operacao em vez do resultado de midia: alerta ativo, fila interna de recomendacoes, dica da Meta com julgamento proprio, saude das integracoes por evidencia de coleta, validade e escopo dos tokens, entregas de digest e custo de LLM no periodo.$ag$,
  delegar_quando = $ag$Alerta, recomendacao pendente, dica da Meta, Opportunity Score, boost, integracao, coleta parada, sincronizacao, token, permissao, escopo, digest, relatorio por e-mail, prontidao, custo de IA ou de LLM.$ag$,
  nao_delegar_quando = $ag$Diagnostico de custo de MIDIA ("por que o CPL subiu") e Analista. A acao sugerida por um alerta e Executor: a Sentinela reporta, ele emite.$ag$
  where codigo = 'AG-07';

update public.agents set papel = $ag$Serve fundamento a quem pedir e responde pela validade da base: politicas da Meta, definicao e leitura de metricas, metodo de otimizacao (Breakdown Effect, fase de aprendizado, gates de escala), operacao da Marketing API, unidade economica e biblioteca de criativo. Declara [VENCIDO] quando o tema passou do revalidar_ate.$ag$,
  delegar_quando = $ag$A pergunta e CONCEITUAL e independe da conta: o que e, como funciona, qual a definicao, qual a boa pratica, o que a Meta permite em tese, por que a metrica se comporta assim. Tambem a propria base de conhecimento e sua validade.$ag$,
  nao_delegar_quando = $ag$Qualquer pergunta que exija dado da conta: se a resposta pede olhar campanha, peca ou numero, o dono e o especialista do setor. O Bibliotecario fundamenta; ele nao consulta a conta.$ag$
  where codigo = 'AG-08';
